Improved the PKGBUILD according to our standard
crystal-linux-packages/jade pull request #1
Opened 2022-10-05 11:45 UTC by Antiz96

Hi,

A round of improvements for the `jade` PKGBUILD:

- Switched all vars to the `${var}` format.
- Reordered the top vars to match the Arch PKGBUILD template order.
- Switch the `license` from `GPLv3` to `GPL3` (it has to be named that way).
- Deleted the extra `GPL` license (if there's multiple licenses, they have to both go into the same `license` array).
- Switched source from `git` to release's archive. Added the integrity check accordingly.
- Modified the `package ()` function to use `install` instead of `mkdir + chmod + install`.

What do you think?

2022-10-06 18:36 UTC, SomethingGeneric approved these changes
LGTM! Thanks for the awesome work, as usual.

2022-10-06 21:14 UTC, FabioLolix commented
Good

2022-10-06 21:25 UTC, FabioLolix commented
Maybe you want to revist build() and add prepare() as for rust guidelines, like in malachite pkgbuild for example

```
prepare() {
    cd "${srcdir}/${pkgname}-${pkgver}"
    cargo fetch --locked --target "${CARCH}-unknown-linux-gnu"
}

build() {
    cd "${srcdir}/${pkgname}-${pkgver}"
    export RUSTUP_TOOLCHAIN=stable
    export CARGO_TARGET_DIR=target
    cargo build --frozen --release --all-features
}
```

2022-10-06 22:21 UTC, SomethingGeneric requested changes

2022-10-06 22:21 UTC, SomethingGeneric commented on PKGBUILD
>  build() {
Let's adapt as @FabioLolix suggests, especially since Malachite follows that already

2022-10-06 22:21 UTC, SomethingGeneric commented on PKGBUILD
>  package() {
^

2022-10-07 09:34 UTC, Antiz96 commented on PKGBUILD
>  build() {
Done in latest commit

2022-10-07 09:34 UTC, Antiz96 commented on PKGBUILD
>  package() {
Done in latest commit

2022-10-07 09:36 UTC, Antiz96 commented
I added the `prepare ()` function and I modified the `build ()` function according to rust guidelines, as suggested by @FabioLolix.
Build was successful.

2022-10-07 21:27 UTC, not-my-segfault approved these changes

2022-10-09 14:04 UTC, merged